//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForeignExchangeMac.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ForeignExchangeMac.Resources.Resource", typeof(Resource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        internal static string AmountNumericValidation {
            get {
                return ResourceManager.GetString("AmountNumericValidation", resourceCulture);
            }
        }
        
        internal static string AmountValidation {
            get {
                return ResourceManager.GetString("AmountValidation", resourceCulture);
            }
        }
        
        internal static string ComandClear {
            get {
                return ResourceManager.GetString("ComandClear", resourceCulture);
            }
        }
        
        internal static string CommandConvert {
            get {
                return ResourceManager.GetString("CommandConvert", resourceCulture);
            }
        }
        
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        internal static string LabelAmount {
            get {
                return ResourceManager.GetString("LabelAmount", resourceCulture);
            }
        }
        
        internal static string LabelSourceRate {
            get {
                return ResourceManager.GetString("LabelSourceRate", resourceCulture);
            }
        }
        
        internal static string LabelTargetRate {
            get {
                return ResourceManager.GetString("LabelTargetRate", resourceCulture);
            }
        }
        
        internal static string PlaceHolrderAmount {
            get {
                return ResourceManager.GetString("PlaceHolrderAmount", resourceCulture);
            }
        }
        
        internal static string SourceRateValidation {
            get {
                return ResourceManager.GetString("SourceRateValidation", resourceCulture);
            }
        }
        
        internal static string TargetRateValidation {
            get {
                return ResourceManager.GetString("TargetRateValidation", resourceCulture);
            }
        }
        
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        internal static string TitleAccessInternet {
            get {
                return ResourceManager.GetString("TitleAccessInternet", resourceCulture);
            }
        }
        
        internal static string TitleIn {
            get {
                return ResourceManager.GetString("TitleIn", resourceCulture);
            }
        }
        
        internal static string TitleIsEqual {
            get {
                return ResourceManager.GetString("TitleIsEqual", resourceCulture);
            }
        }
        
        internal static string TitleLoadRate {
            get {
                return ResourceManager.GetString("TitleLoadRate", resourceCulture);
            }
        }
        
        internal static string TitleReadyConvert {
            get {
                return ResourceManager.GetString("TitleReadyConvert", resourceCulture);
            }
        }
        
        internal static string TitleSettingsInternet {
            get {
                return ResourceManager.GetString("TitleSettingsInternet", resourceCulture);
            }
        }
        
        internal static string TitleSourceRate {
            get {
                return ResourceManager.GetString("TitleSourceRate", resourceCulture);
            }
        }
        
        internal static string TitleStatusInternet {
            get {
                return ResourceManager.GetString("TitleStatusInternet", resourceCulture);
            }
        }
        
        internal static string TitleTargetRate {
            get {
                return ResourceManager.GetString("TitleTargetRate", resourceCulture);
            }
        }
        
        internal static string TitleTheAmount {
            get {
                return ResourceManager.GetString("TitleTheAmount", resourceCulture);
            }
        }
        
        internal static string TitleStatusLoadLocal {
            get {
                return ResourceManager.GetString("TitleStatusLoadLocal", resourceCulture);
            }
        }
        
        internal static string TitleStatusLoadInternet {
            get {
                return ResourceManager.GetString("TitleStatusLoadInternet", resourceCulture);
            }
        }
        
        internal static string TitleStatusNoLoad {
            get {
                return ResourceManager.GetString("TitleStatusNoLoad", resourceCulture);
            }
        }
        
        internal static string TitleStatusLoadError {
            get {
                return ResourceManager.GetString("TitleStatusLoadError", resourceCulture);
            }
        }
    }
}
